questions = [
    "aboni",
    "aĉeti",
    "adreso",
    "aero",
    "afabla",
    "afero",
    "ago",
    "agrabla",
    "aĝo",
    "akcepti",
    "akra",
    "aktiva",
    "akvo",
    "alia",
    "alta",
    "ami",
    "amaso",
    "amiko",
    "amuzi",
    "angulo",
    "anonci",
    "aparato",
    "aparte",
    "aparteni",
    "aperi",
    "aranĝi",
    "arbo",
    "arto",
    "artikolo",
    "asocio",
    "aspekti",
    "ataki",
    "atendi",
    "atenta",
    "atingi",
    "aŭdi",
    "aŭskulti",
    "aŭto",
    "aŭtomobilo",
    "aŭtobuso",
    "aŭtuno",
    "avo",
    "azeno",

    "bani",
    "baro",
    "bati",
    "batali",
    "bazo",
    "bedaŭri",
    "bela",
    "besto",
    "bezoni",
    "biblioteko",
    "biciklo",
    "biero",
    "bildo",
    "bileto",
    "birdo",
    "blanka",
    "blovi",
    "blua",
    "boli",
    "bona",
    "bordo",
    "botelo",
    "bovo",
    "brako",
    "brili",
    "broso",
    "brui",
    "bruli",
    "bruna",
    "brusto",
    "buŝo",
    "butero",
    "butono",

    "celo",
    "centro",
    "certa",
    "cetera",
    "cigaredo",
    "cirklo",

    "ĉambro",
    "ĉapelo",
    "ĉefo",
    "ĉemizo",
    "ĉesi",
    "ĉevalo",
    "ĉielo",

    "danci",
    "danĝero",
    "danki",
    "daŭri",
    "decidi",
    "defendi",
    "dekstra",
    "demandi",
    "densa",
    "dento",
    "desegni",
    "detala",
    "devi",
    "deziri",
    "dio",
    "diferenci",
    "difini",
    "dika",
    "diri",
    "direkto",
    "disko",
    "diskuti",
    "diversa",
    "dividi",
    "doktoro",
    "dolĉa",
    "doloro",
    "domo",
    "domaĝi",
    "doni",
    "donaco",
    "dormi",
    "dorso",
    "drato",
    "dubi",
    "dungi",

    "ebena",
    "eduki",
    "edzo",
    "efektiva",
    "efiki",
    "egala",
    "ekonomio",
    "ekskursi",
    "ekspozicio",
    "ekzameni",
    "ekzemplo",
    "ekzerci",
    "ekzisti",
    "elekti",
    "elektro",
    "energio",
    "erari",
    "esperi",
    "esplori",
    "esprimi",
    "esti",
    "estimi",
    "evolui",

    "facila",
    "fadeno",
    "fajro",
    "fako",
    "fakto",
    "fakturo",
    "fali",
    "fama",
    "familio",
    "fari",
    "farti",
    "feliĉa",
    "fenestro",
    "fero",
    "ferio",
    "fermi",
    "festi",
    "fiksi",
    "filo",
    "filmo",
    "fini",
    "fingro",
    "fiŝo",
    "flago",
    "flanko",
    "flava",
    "floro",
    "flui",
    "flugi",
    "fojo",
    "folio",
    "fondi",
    "fonto",
    "forgesi",
    "forko",
    "formo",
    "forto",
    "fosi",
    "foti",
    "frapi",
    "frato",
    "fraŭlo",
    "fremda",
    "freneza",
    "freŝa",
    "frosto",
    "frue",
    "frukto",
    "fulmo",
    "fumo",
    "funkcio",
    "fuŝi",

    "gaja",
    "gajni",
    "gaso",
    "gasto",
    "gazeto",
    "glacio",
    "glaso",
    "gliti",
    "granda",
    "graso",
    "gratuli",
    "grava",
    "greno",
    "griza",
    "grupo",
    "gusto",
    "gvidi",

    "ĝardeno",
    "ĝeni",
    "ĝenerala",
    "ĝentila",
    "ĝoji",
    "ĝui",
    "ĝusta",

    "halti",
    "haro",
    "haŭto",
    "havi",
    "haveno",
    "hejmo",
    "hela",
    "helpi",
    "herbo",
    "historio",
    "homo",
    "horo",
    "horloĝo",
    "hotelo",
    "hundo",

    "ĥoro",

    "ideo",
    "idealo",
    "imagi",
    "imiti",
    "industrio",
    "infano",
    "informi",
    "insekto",
    "insigno",
    "instrui",
    "insulo",
    "inteligenta",
    "intenci",
    "interesi",
    "interna",
    "inviti",
    "iri",

    "jaro",
    "juĝi",
    "juna",
    "jupo",
    "justa",

    "ĵeti",

    "kadro",
    "kafo",
    "kajero",
    "kalendaro",
    "kalkuli",
    "kampo",
    "kanti",
    "kapo",
    "kapabla",
    "kapti",
    "kara",
    "karavano",
    "karbo",
    "karto",
    "kasedo",
    "kaŝi",
    "kato",
    "kaŭzo",
    "kazo",
    "kelka",
    "kisi",
    "klara",
    "klaso",
    "klini",
    "klopodi",
    "klubo",
    "knabo",
    "kolo",
    "kolekti",
    "koleri",
    "koloro",
    "kombi",
    "komenci",
    "komerci",
    "komforta",
    "komisii",
    "komitato",
    "kompari",
    "kompati",
    "kompreni",
    "komputi",
    "komuna",
    "komuniki",
    "koni",
    "koncerni",
    "kondiĉo",
    "konduki",
    "konfesi",
    "kongreso",
    "konkreta",
    "konsenti",
    "konservi",
    "konsideri",
    "konsili",
    "konsisti",
    "konstanta",
    "konstrui",
    "kontakti",
    "kontenta",
    "kontroli",
    "konvena",
    "konvinki",
    "kopii",
    "koro",
    "korbo",
    "korespondi",
    "korpo",
    "korto",
    "kosto",
    "kostumo",
    "koverto",
    "kovri",
    "krajono",
    "krei",
    "kredi",
    "kreski",
    "krii",
    "kruela",
    "kruro",
    "kudri",
    "kuiri",
    "kuko",
    "kulero",
    "kulpa",
    "kulturo",
    "kupono",
    "kuri",
    "kuraci",
    "kuraĝa",
    "kurso",
    "kuŝi",
    "kutimo",
    "kuzo",
    "kvadrato",
    "kvalito",
    "kvanto",

    "labori",
    "laca",
    "lago",
    "lakto",
    "lando",
    "lango",
    "larĝa",
    "lasi",
    "lasta",
    "lavi",
    "leciono",
    "legi",
    "legomo",
    "leĝo",
    "lerni",
    "lerta",
    "letero",
    "levi",
    "libera",
    "libro",
    "ligi",
    "ligno",
    "limo",
    "lingvo",
    "linio",
    "lipo",
    "listo",
    "lito",
    "litero",
    "literaturo",
    "loĝi",
    "loko",
    "longa",
    "ludi",
    "lumo",
    "luno",

    "mano",
    "manĝi",
    "maniero",
    "manki",
    "mantelo",
    "maro",
    "marko",
    "marŝi",
    "mastro",
    "maŝino",
    "mateno",
    "materio",
    "materialo",
    "mveblo",
    "medio",
    "membro",
    "memori",
    "mendi",
    "meriti",
    "meti",
    "metalo",
    "metodo",
    "metro",
    "mezo",
    "mezuri",
    "miksi",
    "militi",
    "minuto",
    "miri",
    "moderna",
    "moki",
    "mola",
    "momento",
    "mono",
    "monato",
    "mondo",
    "monto",
    "montri",
    "morti",
    "movi",
    "multa",
    "muro",
    "muso",
    "muŝo",
    "muzeo",
    "muziko",

    "nacio",
    "naĝi",
    "naski",
    "naturo",
    "nazo",
    "nebulo",
    "necesa",
    "neĝo",
    "nepo",
    "nepra",
    "neŭtrala",
    "nevo",
    "nigra",
    "nivelo",
    "nokto",
    "nomo",
    "nombro",
    "nordo",
    "normala",
    "noti",
    "nova",
    "nubo",
    "numero",

    "obei",
    "objekto",
    "odori",
    "ofico",
    "ofta",
    "okazi",
    "okicidento",
    "okulo",
    "okupi",
    "oleo",
    "onklo",
    "opinio",
    "oro",
    "ordo",
    "ordinara",
    "ordoni",
    "orelo",
    "organo",
    "organizi",
    "oriento",
    "originalo",
    "osto",
    "ovo",

    "paco",
    "pagi",
    "paĝo",
    "paki",
    "palpi",
    "pano",
    "pantalono",
    "papero",
    "paro",
    "pardoni",
    "parko",
    "paroli",
    "parto",
    "pasi",
    "pasporto",
    "paŝi",
    "patro",
    "peco",
    "peni",
    "pendi",
    "pensi",
    "pentri",
    "perdi",
    "perfekta",
    "periodo",
    "permesi",
    "persono",
    "peti",
    "peza",
    "piedo",
    "piki",
    "pilko",
    "plaĉi",
    "plafono",
    "plano",
    "planko",
    "planto",
    "plasto",
    "plena",
    "plendi",
    "plezuro",
    "plori",
    "plumo",
    "plura",
    "pluvo",
    "poemo",
    "poento",
    "poezio",
    "polico",
    "politiko",
    "ponto",
    "popolo",
    "populara",
    "pordo",
    "porti",
    "postuli",
    "poŝo",
    "poŝto",
    "poto",
    "povi",
    "praktiko",
    "prava",
    "precipe",
    "preciza",
    "preferi",
    "preĝi",
    "prelegi",
    "premi",
    "premio",
    "preni",
    "prepari",
    "presi",
    "preta",
    "prezo",
    "prezenti",
    "prezidi",
    "principo",
    "printempo",
    "problemo",
    "produkti",
    "profunda",
    "programo",
    "pregresi",
    "projekto",
    "proksima",
    "promeni",
    "promesi",
    "proponi",
    "propra",
    "provi",
    "prunti",
    "pruvi",
    "publiko",
    "puni",
    "punkto",
    "pupo",
    "pura",
    "puŝi",

    "rado",
    "radio",
    "rajto",
    "rakonti",
    "rando",
    "rango",
    "rapida",
    "raporti",
    "redakti",
    "regi",
    "regiono",
    "regulo",
    "reĝo",
    "reklami",
    "rekomendi",
    "rekta",
    "religio",
    "renkonti",
    "respondi",
    "resti",
    "reto",
    "revuo",
    "rezulto",
    "ricevi",
    "riĉa",
    "ridi",
    "rigardi",
    "rilati",
    "rimarki",
    "rimedo",
    "ripeti",
    "ripozi",
    "rivero",
    "rizo",
    "robo",
    "romano",
    "rompi",
    "rondo",
    "rozo",
    "rubriko",
    "ruĝa",
    "ruli",

    "saĝa",
    "sako",
    "salo",
    "salono",
    "salti",
    "saluti",
    "sama",
    "sana",
    "sango",
    "sankta",
    "sata",
    "savi",
    "scii",
    "scienco",
    "seĝo",
    "seka",
    "sekretario",
    "sekso",
    "sekvi",
    "semajno",
    "senco",
    "sendi",
    "senti",
    "serĉi",
    "serio",
    "serioza",
    "servi",
    "sezono",
    "sidi",
    "signo",
    "signifi",
    "silenti",
    "simila",
    "simpla",
    "sinjoro",
    "sistemo",
    "situacio",
    "skatolo",
    "skribi",
    "socio",
    "soifi",
    "sola",
    "soldato",
    "solvi",
    "somero",
    "soni",
    "speciala",
    "spegulo",
    "sperti",
    "spezi",
    "spico",
    "spiri",
    "sporto",
    "stacio",
    "stari",
    "stato",
    "stelo",
    "stranga",
    "strato",
    "streĉi",
    "studi",
    "studento",
    "stulta",
    "subita",
    "sudo",
    "suferi",
    "sufiĉa",
    "sukcesi",
    "sukero",
    "sumo",
    "suno",
    "supozi",
    "supro",

    "ŝafo",
    "ŝajni",
    "ŝanco",
    "ŝanĝi",
    "ŝati",
    "ŝerci",
    "ŝipo",
    "ŝiri",
    "ŝlosi",
    "ŝnuro",
    "ŝranko",
    "ŝtato",
    "ŝteli",
    "ŝtofo",
    "ŝtono",
    "ŝtrumpo",
    "ŝtupo",
    "ŝuo",

    "tablo",
    "tabulo",
    "tago",
    "taso",
    "tasko",
    "taŭga",
    "teo",
    "teatro",
    "tegmento",
    "teksto",
    "telefono",
    "telero",
    "televidi",
    "temo",
    "tempo",
    "teni",
    "teorio",
    "tero",
    "teruro",
    "timi",
    "tiri",
    "tondi",
    "tradicio",
    "traduki",
    "trafi",
    "trakti",
    "tranĉi",
    "trankvila",
    "trinki",
    "trovi",
    "truo",
    "tuko",
    "turismo",
    "turisto",
    "turni",
    "tuŝi",
    "tuta",

    "ŭato",
    "vato",

    "universala",
    "universitato",
    "urbo",
    "utila",
    "uzi",

    "vagono",
    "valida",
    "valoro",
    "varma",
    "vasta",
    "veki",
    "veni",
    "vendi",
    "venki",
    "vento",
    "vero",
    "verda",
    "verko",
    "vespero",
    "vesto",
    "vetero",
    "veturi",
    "viando",
    "vico",
    "vidi",
    "vigla",
    "vilaĝo",
    "vino",
    "vintro",
    "viro",
    "viŝi",
    "vitro",
    "vivi",
    "vizaĝo",
    "viziti",
    "voĉo",
    "vojo",
    "vojaĝi",
    "voki",
    "voli",
    "volvi",
    "vorto",
    "vosto",

    "zorgi"
]
